version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/xbot
      - SECRET_KEY=cryptoguys
      - FERNET_KEY=IJk7F2n4Quyid66Q6hn1ryqFeubBqInOc_gR6TO5Ov8=
      - FLASK_APP=main.py
      - FLASK_ENV=production
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade && gunicorn --bind 0.0.0.0:5000 main:app"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xbot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
